Repository abhishekraoas/MCA-Alumni-Network, pull requests merged in 2024-10, with the labels that each got.

#7 #Add Create greetings.yml
  .github/workflows/greetings.yml
Labels: gssoc-ext, level1

#22 Added the Navbar Routes Functionlaity
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/About.jsx
  client/src/components/Contact.jsx
  client/src/components/Header.jsx
  client/src/components/Login.jsx
  client/src/components/OurAlumni.jsx
  client/src/components/ScrollTop.jsx
  client/src/components/SignUp.jsx
Labels: gssoc-ext, hacktoberfest-accepted

#109 README.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, Level1

#119 This is fix for issue #118 cursor effect
  client/package-lock.json
  client/src/components/Home.jsx
  client/src/components/ImageWithCursorEffect.jsx
  server/controllers/user.controllers.js
  server/package-lock.json
  server/package.json
Labels: gssoc-ext, hacktoberfest-accepted, Level1

#143 Update server.js
  client/src/components/Home.jsx
  client/src/components/Register.jsx
  server/controllers/user.controllers.js
  server/server.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#151 Social media icons problem fixed
  client/src/components/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#155 Re-Design About Us page with modern ui features
  client/src/components/About.jsx
  client/src/components/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#171 updated-footer
  client/src/components/Footer.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#167 new feature : ScrollOnTop button
  client/src/App.jsx
  client/src/components/ScrollToTop.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#177 Add new feature:Enhanced UI by adding proper margins and implementing…
  client/src/components/OurAlumni.jsx
  client/src/components/SocialMedia.jsx
  client/src/components/UserCards.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#188 fixed the broken image in register section
  client/package-lock.json
  client/src/components/Register.jsx
Labels: bug, gssoc-ext, hacktoberfest-accepted, level1

#191 [UI Enhancement] : added Gsap animation to navbar and home page fixes #134
  client/package-lock.json
  client/package.json
  client/src/components/Header.jsx
  client/src/components/Home.jsx
  client/src/components/gsap.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#192 #145 Improve Form Handling and UI Enhancements for Sign Up Page
  client/package-lock.json
  client/src/components/Login.jsx
  client/src/components/Register.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#209 Feature/scrollbaragain : Done #180 and #190
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Login.jsx
  client/src/components/Register.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#215 updated PR
  client/package-lock.json
  client/src/components/Login.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#218 Focused navlink in navbar
  client/src/components/Header.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#245 Fixed #236, Resolved the select button bug
  client/package-lock.json
  client/src/components/Register.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#240 UI Enhanced of ContactUs Page
  client/src/components/Contact.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#242 Implement PR Issue Checker Workflow
  .github/workflows/pr-checker.yaml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#250 Added-Password-Recovery-feature #241
  client/src/App.jsx
  client/src/components/ForgotPassword.jsx
  client/src/components/InputField.jsx
  client/src/components/Login.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2
